import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userContext";

import clsx from "clsx";

import localFont from "next/font/local";
import AuthProvider from "@components/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const unicorn = localFont({
  // src: "my-app/public/font/Jumping Unicorn.ttf",
  src: "../../public/font/JumpingUnicorn.ttf",
  variable: "--font-unicorn",
});
export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          geistSans.variable,
          unicorn.variable,
          geistMono.variable,
          "antialiased"
        )}
      >
        {" "}
        <AuthProvider>
          <UserProvider>{children} </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
